import robby
#import numpy as np
from utils import *
import random
POSSIBLE_ACTIONS = ["MoveNorth", "MoveSouth", "MoveEast", "MoveWest", "StayPut", "PickUpCan", "MoveRandom"]
rw = robby.World(10, 10)
rw.graphicsOff()


def sortByFitness(genomes):
    return map(list, zip(*sorted([(fitness(g), g) for g in genomes])))


def randomGenome(length):
    """
    :param length:
    :return: string, random integers between 0 and 6 inclusive
    """
    return "".join(map(str, [random.randint(0,6) for i in range(length)])) 


def makePopulation(size, length):
    """
    :param size - of population:
    :param length - of genome
    :return: list of length size containing genomes of length length
    """
    return [randomGenome(length) for _ in range(size)]


def fitness(genome, steps=200, init=0.50):
    """
    :param genome: to test
    :param steps: number of steps in the cleaning session
    :param init: amount of cans
    :return:
    """
    scores = []
    for _ in range(25):
        if type(genome) is not str or len(genome) != 243:
            raise Exception("strategy is not a string of length 243")
        for char in genome:
            if char not in "0123456":
                raise Exception("strategy contains a bad character: '%s'" % char)
        if type(steps) is not int or steps < 1:
            raise Exception("steps must be an integer > 0")
        if type(init) is str:
            # init is a config file
            rw.load(init)
        elif type(init) in [int, float] and 0 <= init <= 1:
            # init is a can density
            rw.goto(0, 0)
            rw.distributeCans(init)
        else:
            raise Exception("invalid initial configuration")

        score = 0
        for _ in range(steps):
            p = rw.getPerceptCode()
            action = POSSIBLE_ACTIONS[int(genome[p])]
            score += rw.performAction(action)
        scores.append(score)

    return Average(scores)


def evaluateFitness(fitnesses):
    """
    :param population:
    :return: a pair of values: the average fitness of the population as a whole and the fitness of the best individual
    in the population.
    """
    return (Average(fitnesses), max(fitnesses))


def crossover(genome1, genome2):
    """
    :param genome1:
    :param genome2:
    :return: two new genomes produced by crossing over the given genomes at a random crossover point.
    """
    split = random.randint(1, len(genome1) - 1)
    child1 = genome1[:split] + genome2[split:]
    child2 = genome2[:split] + genome1[split:]
    return (child1, child2)


def mutate(genome, mutationRate):
    """
    :param genome:
    :param mutationRate:
    :return: a new mutated version of the given genome.
    """
    tmp = ""
    for chrom in genome:
        if random.random() <= mutationRate:
            randmut = random.randint(0,6)
            while str(randmut) == chrom:
                randmut = random.randint(0,6)
            tmp += str(randmut)
        else:
            tmp += chrom
    return tmp


# population must be sorted
def selectPair(population):
    """
    :param population:
    :return: two genomes from the given population using fitness-proportionate selection.
    This function should use RankSelection,
    """
    weights = range(1, len(population) + 1)
    individual1 = weightedChoice(population, weights)
    individual2 = weightedChoice(population, weights)
    return (individual1, individual2)


def runGA(populationSize, crossoverRate, mutationRate, logFile=""):
    """
    :param populationSize: 
    :param crossoverRate: 
    :param mutationRate: 
    :param logFile: 
    :return: The optional logFile parameter is a string specifying the name of a text file in which to
    store the data generated by the GA, for plotting purposes. 
    Is the main GA program, which takes the population size, crossover rate (pc), and mutation rate (pm) as parameters. 
    """
    genome_length = 243
    generations = 3000
    population = makePopulation(populationSize, genome_length)

    if logFile != "":
        f = open(logFile, "w+")
    print("Poplation size:", populationSize)

    for i in range(generations+1):
        weights, population = sortByFitness(population)
        avg_fitness, highest_fitness = evaluateFitness(weights)
        
        if i % 10 == 0:
            if logFile != "":
                f.write("{} {:.02f} {:.02f} {}\n".format(i, avg_fitness, highest_fitness, population[0]))
            print("Generation {}: average fitness {:.02f}, best fitness {:.02f}".format(i, avg_fitness, highest_fitness))
            
        new_pop = []
        while len(new_pop) < populationSize:
            genome1, genome2 = selectPair(population)
            if random.random() <= crossoverRate:
                genome1, genome2 = crossover(genome1, genome2)
            new_pop += [mutate(genome1, mutationRate), mutate(genome2, mutationRate)]
        population = new_pop

    if logFile != "":
        f.close()
        print("Results saved in file", logFile)


def test_FitnessFunction():
    f = fitness(rw.strategyM)
    print("Fitness for StrategyM : {0}".format(f))


# runGA(100, 0.7, 1, "")

runGA(100, 0.5, 0.005, "robby_run2.txt")